sudo: required
language: generic

matrix:
  include:
# Former Makefile builder
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: DISTRO=native BUILDER=make LANGUAGE=cc
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: DISTRO=native BUILDER=make LANGUAGE=python
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: DISTRO=native BUILDER=make LANGUAGE=java
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: DISTRO=native BUILDER=make LANGUAGE=csharp

    - os: osx
      language: cpp
      compiler: clang
      env: DISTRO=native BUILDER=make LANGUAGE=cc
    - os: osx
      language: cpp
      compiler: clang
      env: DISTRO=native BUILDER=make LANGUAGE=python
    - os: osx
      language: cpp
      compiler: clang
      env: DISTRO=native BUILDER=make LANGUAGE=java
    - os: osx
      language: cpp
      compiler: clang
      env: DISTRO=native BUILDER=make LANGUAGE=csharp
# Experimental CMake Builder
    - os: linux
      language: generic
      services:
        - docker
      env: DISTRO=alpine BUILDER=cmake
    - os: linux
      language: generic
      services:
        - docker
      env: DISTRO=ubuntu BUILDER=cmake

    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: DISTRO=native BUILDER=cmake
    - os: linux
      dist: trusty
      language: cpp
      compiler: clang
      env: DISTRO=native BUILDER=cmake

    - os: osx
      language: cpp
      compiler: gcc
      env: DISTRO=native BUILDER=cmake
    - os: osx
      language: cpp
      compiler: clang
      env: DISTRO=native BUILDER=cmake

install:
  - ./.travis/install.sh

script:
  - ./.travis/script.sh


